### ISSUE TITLE
addhooks() got deprecated in pytest git version

### ISSUE THREAD

**Issue by The-Compiler** [davehunt/pytest-html#10]
It's probably rather early to report this, but I thought I'd do so anyways.

When using `pytest-html` with the latest pytest version from their [git repo](https://github.com/pytest-dev/pytest) with `-rw` (show warning texts) I get this:

```
WI2 /.../pytest_html/plugin.py:28 use pluginmanager.add_hookspecs instead of deprecated addhooks() method.
```

**Comment by davehunt** [comment]
Thanks @The-Compiler, we could check for `add_hookspecs` and use it if it exists, reverting to `addhooks`. Once a new version of pytest with this change is released we can either increase the dependency or leave this check in place.

**Comment by The-Compiler** [comment]
f8a5a5c934b335cf87fc463abfa3fbcee779c980 removed the hooks mechanism, so this isn't an issue anymore.
