### ISSUE TITLE
Not able to customize the environment section of the report

### ISSUE THREAD

**Issue by hprem** [davehunt/pytest-html#17]
I am trying to add some content to the Environment section of the report
On adding the following code to my conftest.py file, 
```python
@pytest.fixture(autouse=True)
def _environment(request):
    request.config._html.environment.append(('foo', 'bar'))
```
I get the error
```
>       request.config._html.environment.append(('foo', 'bar'))
E       AttributeError: 'Config' object has no attribute '_html'
```

Has the path to _html changed?

Regards
Prem

**Comment by hprem** [comment]
Sorry... I didn't seem to have "--html" parameter in my py.test cmd line, by mistake. Adding that solved this

**Comment by davehunt** [comment]
Yes, this is only present when the HTML report plugin is in use. You can easily check in your code using `if hasattr(config, '_html')`.
