### ISSUE TITLE
Environment is not populated when using pytest-xdist

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-html#18]
The environment section in the HTML report is missing when we run tests in parallel using pytest-xdist. I'm hoping that @RonnyPfannschmidt can take a look and suggest how we can fix it. :smile:

**Comment by RonnyPfannschmidt** [comment]
its impossible to share the information as is

the current implementation basically relies on "global variables"

pytest-xdist has the concept of a `slaveoutput`, which i a dictionary

you can pass normal strings/numbers with ease using that

the objects you should interact with on the slave are
`config.slaveinput` and `config.slaveoutput`

to finish the reporting there is a hook called `pytest_testnodedown(node, error)`
the `node` will have a `slaveoutput` attribute matching the dictionary of the slave

so you can just set `config.slaveoutput['environment'] = environment` and access it on the master in the testnodedown hook and add each nodes environment to a list for use in reporting


to handle configuration there is the `pytest_configure_node(node)` hook, the node will have a slaveinput attribute where you can add extra inputs

**Comment by davehunt** [comment]
Thanks @RonnyPfannschmidt, I've been able to fix this in pull #19. Would you be able to take a look and let me know if there's anything concerning in my changes?
