### ISSUE TITLE
[Feature request] Able to add "html" to addopts in setup.cfg

### ISSUE THREAD

**Issue by rarelam** [davehunt/pytest-html#23]
Hi, 

I would like to request to add "html" to addopts in setup.cfg.

Thank you

**Comment by The-Compiler** [comment]
I'm guessing you mean the `[pytest]` section there? That works fine for me. How doesn't it for you?

```ini
[pytest]
addopts = --html foo.html
```

**Comment by davehunt** [comment]
As mentioned in https://github.com/davehunt/pytest-selenium/issues/37 you should already be able to do this:

```ini
[pytest]
addopts = --html=/path/to/results.html
```

**Comment by rarelam** [comment]
I was expecting a easier way to add HTML on setup.cfg.

But addopts will work fine for me too.

Thank you.
