### ISSUE TITLE
Add how to add screenshots to html report to documentation

### ISSUE THREAD

**Issue by frimmy** [davehunt/pytest-html#26]
I love this plug in, is this included in pytest by default now?
I've incorporated in jenkins, and it works well, save for the screenshot bit. 

Any help?

**Comment by frimmy** [comment]
ah --- perhaps pytest updated the way pytest_runtest_makereport is implemented as well 
```(item, call)``` instead of ```(__multicall__, item)``` for args

**Comment by davehunt** [comment]
I'm glad you like the plugin! It's not in pytest by default, and suspect it will remain a plugin as this is not an essential core feature.

I've just updated to remove the use of `__multicall__` from the README and tests, as it has been deprecated in the latest version of pytest. For an example of including an image in your HTML report, you can see [this test](https://github.com/davehunt/pytest-html/blob/0500aa622fab4e9bc6db671339bab347cb281d2b/test_pytest_html.py#L223-L240), or see how this is done [in pytest-selenium](https://github.com/davehunt/pytest-selenium/blob/db3f61afa2477735a6ec8bf29737e011fd7bdc9b/pytest_selenium/pytest_selenium.py#L139-L148).

I hope this helps, however please feel free to reopen this issue with more details if you're still having problems.
