### ISSUE TITLE
Show text output for succeeded runs

### ISSUE THREAD

**Issue by davidedelvento** [davehunt/pytest-html#44]
I'm trying to replicate #11 for a purely text case, but I can't figure out if it's possible and if yes how. Pointer to documentation would help. Neither starting from the example in #11 nor from the one in the front page helped (at most I got "No log output captured." section)

Thanks!

**Comment by davehunt** [comment]
Fixed in https://github.com/davehunt/pytest-html/commit/77fef3cc37023fc696e9b4a560741dc6eba7812e and released as 1.8.1.

**Comment by davidedelvento** [comment]
Wow, that was fast, thanks!
