### ISSUE TITLE
AttributeError: 'TestReport' object has no attribute 'extra'

### ISSUE THREAD

**Issue by reddypdl** [davehunt/pytest-html#7]
Tried to add the code below, but got error - AttributeError: 'TestReport' object has no attribute 'extra'

from py.xml import html
from html import extras

def pytest_runtest_makereport(__multicall__, item):
    report = __multicall__.execute()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            url = TestSetup.selenium.current_url
            report.extra.append(extras.url(url))
            screenshot = TestSetup.selenium.get_screenshot_as_base64()
            report.extra.append(extras.image(screenshot, 'Screenshot'))
            html = TestSetup.selenium.page_source.encode('utf-8')
            report.extra.append(extra.text(html, 'HTML'))
            report.extra.append(extra.html(html.div('Additional HTML')))
        report.extra = extra
    return report

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\Python27\lib\site-packages\_pytest\main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "D:\Python27\lib\site-packages\_pytest\main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
...........................
pytest_runtest_makereport
INTERNALERROR>     report.extra.append(extra.text(item._obj.__doc__.strip(), 'HTML'))
INTERNALERROR> AttributeError: 'TestReport' object has no attribute 'extra'

**Comment by davehunt** [comment]
It looks like you've just copy/pasted the example from the README. There was an error in this were the code tries to access report.extra before it's set, which I've now fixed. I've also simplified the example because it was relying on a TestSetup having a Selenium object.
