### ISSUE TITLE
Add captured output (stdout, stderr) to report

### ISSUE THREAD

**Issue by ionelmc** [davehunt/pytest-html#8]
Captured logs are included but captured stdout/stderr is not.

(tested with pytest 2.7.1)

**Comment by davehunt** [comment]
Could you elaborate on what you're expecting to see in the HTML report?

**Comment by ionelmc** [comment]
So in terminal I get something like this:
```
============================= FAILURES ===================================
________________ test_blabla ________________________
Traceback (most recent call last):
  blablabla
---------------------------------------------------- Captured log --------------------------------------------------

stuff.py                284 DEBUG    STUFF I LOGGED
--------------------------------------------- Captured stderr setup ---------------------------------------------
STUFF I PRINTED
```
But in the html report I don't see the stderr stuff anymore

**Comment by davehunt** [comment]
> But in the html report I don't see the stderr stuff anymore

By saying 'anymore' are you suggesting this is a regression? Currently only the long string representation of the failure is included in the HTML report, see https://github.com/davehunt/pytest-html/blob/master/pytest_html/plugin.py#L110

Adding stdout and stderr would certainly be a nice enhancement.
